on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jpetrucciani/mypy-check@master
        with:
          requirements: types-requests
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jpetrucciani/black-check@master
  tests:
    runs-on: ubuntu-latest
    needs: [mypy, black]
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    name: python ${{ matrix.python-version }} tests
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: install requirements
        run: pip install -r requirements.dev.txt
      - name: run Pytest
        run: pytest
